### ISSUE TITLE
[Feature request]: Improve pause functionality

### ISSUE THREAD

**Issue by nordowl** [Matistan/MinecraftManhunt#1]
First of all, thanks for making this plugin - works very well!

Using `/manhunt pause` I noticed that the day/night cycle did continue while manhunt was paused. I think it would be nice if the day/night cycle was paused during a paused manhunt game.

You could probably go as far as to set the game tick speed to 0 in newer versions that support this - just so that mobs are unable to move during a pause. Currently, hostile mobs can run up to you and surround you, leaving you in a tricky situation once you unpause (haven't tried it, but that's my theory).

**Comment by Matistan** [comment]
Hi there! 
Thank you so much for using and enjoying my plugin! I genuinely appreciate it. Also, I'm grateful for your advice.

Regarding the day/night cycle issue, I'll fix that right away. As for setting the tick speed to 0, I'll see if I'll make it, because I want it to be compatible for all 1.16+ versions. Your theory about hostile mobs is indeed true, so I'll try to find potential solutions.

**Comment by Matistan** [comment]
Ok, so I fixed the day/night issue, but idk how to set the game tick speed to 0, idk if this is even possible. If mobs surrounded the player during the pause, they can kill them while still being paused, and also after resuming the game, everyone has 10 seconds of invincibility. I hope that this is enough, and I will close the issue.

**Comment by nordowl** [comment]
Thank you for taking care!
